updatee

diff --git a/.github/workflows/main_monstersurvival.yml b/.github/workflows/main_monstersurvival.yml
--- a/.github/workflows/main_monstersurvival.yml
+++ b/.github/workflows/main_monstersurvival.yml
@@ -70,6 +70,10 @@ jobs:
           echo "SECRETKEY=${{ secrets.SECRETKEY }}" >> $GITHUB_ENV
           echo "EXPIRESIN=${{ secrets.EXPIRESIN }}" >> $GITHUB_ENV
 
+      - name: Check if main.js is built
+        run: |
+          if [ -f dist/main.js ]; then echo "main.js exists"; else echo "main.js not found"; exit 1; fi
+
       - name: 'Deploy to Azure Web App'
         id: deploy-to-webapp
         uses: azure/webapps-deploy@v3
